### ISSUE TITLE
Typo in "Measuring rule interest – support and confidence" (Chapter 8).-..

### ISSUE THREAD

**Issue by coforfe** [PacktPublishing/Machine-Learning-with-R-Third-Edition#1]
Hello,

In chapter 8, where it is covered the **"Arules"** algorithm, in this section where it is defined *support* and *confidence* the formula for the *support* is missing. It appears the formula with the *confidence* which is repeated below.

Thanks,
Carlos Ortega.

**Comment by coforfe** [comment]
And thanks for your book, it is very well written and the examples very appropriate.
Congratulations.
Carlos.

**Comment by dataspelunking** [comment]
Hi Carlos, in preparation for the upcoming 4th edition of Machine Learning with R, I'm closing out a couple of issues here on GitHub for the 3rd edition. I'm happy to say that this issue will be fixed, although sadly, I cannot make the fix retroactively. Thanks for bringing it to my attention as well as the kind feedback!
